print("hello world, seious day")
print("hi")
print("stupid")
print("four")
print("five")
print("sixsense")
print("i'm test1 hi")
print("nice to meet you")
print("test중입니다. 무엇을? push가 뜨는지 안뜨는지")
print("i'm test2 hello")

print("hello, jun")
